packages:
  - '.'
overrides:
  immutable: 5.1.9
  postcss: 8.5.26
  tmp: 0.2.7
  'brace-expansion@<2': 1.1.16
  'brace-expansion@^2': 2.1.2
  'minimatch@^3': 3.1.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
